name: Build


on:
 push:
   branches: [ main ]
 pull_request:
   branches: [ main ]


jobs:
 build:


   runs-on: ubuntu-latest


   strategy:
     matrix:
       node-version: [18.x]


   name: Build, Lint and Test
   steps:
   - uses: actions/checkout@v2
   - name: Use Node.js ${{ matrix.node-version }}
     uses: actions/setup-node@v1
     with:
       node-version: ${{ matrix.node-version }}


   - name: Install Dependencies
     run: npm install


   - name: Check Build
     run: npm run build
    
   - name: Check Lint
     run: npm run lint


   - name: Check Code Formatting
     run: npm run prettier-check
